<?php

/**
 * @file
 * Primary module hooks for farmOS Cool Farm Platform module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;

/**
 * Implements hook_farm_entity_bundle_field_info().
 */
function farm_cfp_farm_entity_bundle_field_info(EntityTypeInterface $entity_type, $bundle) {
  $fields = [];

  if ($entity_type->id() == 'log' && $bundle == 'calculation') {
    $options = [
      'type' => 'integer',
      'label' => t('Assessment year'),
      'min' => 1980,
      'max' => 2100,
    ];
    $fields['calculation_year'] = \Drupal::service('farm_field.factory')->bundleFieldDefinition($options);
  }

  return $fields;
}

/**
 * Implements hook_entity_bundle_field_info_alter().
 */
function farm_cfp_entity_bundle_field_info_alter(&$fields, EntityTypeInterface $entity_type, $bundle) {
  // Unhide the data fields for calculation logs.
  if ($entity_type->id() == 'log' && $bundle == 'calculation') {
    $fields_to_unhide = [
      'data_sent',
      'data_received',
      'metadata',
    ];
    foreach ($fields_to_unhide as $name) {
      if (!empty($fields[$name])) {
        $view_display_options = $fields[$name]->getDisplayOptions('view');
        $view_display_options['region'] = TRUE;
        $view_display_options['type'] = 'pretty_yaml';
        $fields[$name]->setDisplayOptions('view', $view_display_options);
        $form_display_options = $fields[$name]->getDisplayOptions('form');
        $form_display_options['region'] = TRUE;
        $fields[$name]->setDisplayOptions('form', $form_display_options);
      }
    }
  }
}

/**
 * Implements hook_form_alter().
 */
function farm_cfp_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id === 'log_calculation_edit_form') {
    $readonly_fields = [
      'data_sent',
      'data_received',
      'metadata',
    ];

    foreach ($readonly_fields as $field_name) {
      if (isset($form[$field_name])) {
        $form[$field_name]['#disabled'] = TRUE;
      }
    }
  }
}

/**
 * Implements hook_entity_operation().
 */
function farm_cfp_entity_operation_alter(array &$operations, EntityInterface $entity) {
  if ($entity->getEntityTypeId() === 'log' && $entity->bundle() === 'calculation') {

    // Add a Duplicate Assessment operation.
    $url = Url::fromRoute('farm_cfp.add_assessment', [], [
      'query' => ['source' => $entity->id()],
    ]);

    $operations['duplicate_assessment'] = [
      'title' => t('Duplicate Assessment'),
      'weight' => 10,
      'url' => $url,
    ];
  }
}
