<?php

/**
 * @file
 * Primary module hooks for farmOS Cool Farm Platform module.
 */

use Drupal\Core\Entity\EntityTypeInterface;

/**
 * Implements hook_farm_entity_bundle_field_info().
 */
function farm_cfp_farm_entity_bundle_field_info(EntityTypeInterface $entity_type, $bundle) {
  $fields = [];

  if ($entity_type->id() == 'log' && $bundle == 'observation') {
    $options = [
      'type' => 'boolean',
      'label' => t('Is CFP Assessment'),
      'description' => t('This is a Cool Farm Platform assessment log.'),
      'form_display_options' => [
        'weight' => 100,
      ],
    ];
    $fields['cfp'] = \Drupal::service('farm_field.factory')->bundleFieldDefinition($options);
  }

  return $fields;
}
